name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v .

      - name: Compress
        run: tar -czvf litra-macos-arm64.tar.gz litra

      - name: Generate Hash
        run: shasum -a 256 litra-macos-arm64.tar.gz > litra-macos-arm64.tar.gz.sha256

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/gzip
          asset_path: litra-macos-arm64.tar.gz
          asset_name: litra-macos-arm64.tar.gz

      - name: Upload Hash
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: text/plain
          asset_path: litra-macos-arm64.tar.gz.sha256
          asset_name: litra-macos-arm64.tar.gz.sha256
